# Generated by Django 5.2.6 on 2025-09-30 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('company_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('host_name', models.CharField(max_length=100)),
                ('host_department', models.CharField(max_length=100)),
                ('visit_purpose', models.CharField(choices=[('meeting', 'Meeting'), ('interview', 'Interview'), ('delivery', 'Delivery'), ('maintenance', 'Maintenance'), ('consultation', 'Consultation'), ('training', 'Training'), ('examination', 'Examination'), ('other', 'Other')], max_length=20)),
                ('visit_purpose_details', models.TextField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('expected_duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], default='checked_in', max_length=15)),
                ('visitor_badge_number', models.CharField(blank=True, max_length=10, null=True)),
                ('items_carried', models.TextField(blank=True, help_text='List any bags, laptops, or other items', null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], max_length=15)),
                ('make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_id_number', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=200)),
                ('parking_spot', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('parked', 'Parked'), ('departed', 'Departed')], default='parked', max_length=10)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='main.visitor')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
