# Generated by Django 5.2.6 on 2025-09-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visitor_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasnebuser',
            name='role',
            field=models.CharField(choices=[('security', 'Security'), ('ict_officer', 'ICT Officer'), ('admin', 'Admin')], default='security', max_length=20),
        ),
    ]
